server {

    listen 80;

    server_name api.eothawn.com;

    root /var/www/back-end/public;

    index index.php;

    location / {

        try_files $uri /index.php?$query_string;

    }

    location ~ \.php$ {

        include fastcgi_params;

        fastcgi_pass unix:/run/php-fpm/www.sock;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        include fastcgi.conf;
    }

    access_log /var/log/nginx/backend_access.log;
    error_log /var/log/nginx/backend_error.log;
}
