server {

    listen 80;

    server_name agenda.eothawn.com;

    root /var/www/front-end;

    index login.html;

    location / {

        try_files $uri $uri/ /index.html;
    }
    
    access_log /var/log/nginx/frontend_access.log;
    error_log /var/log/nginx/frontend_error.log;
}